# kubernetes/monitoring/alertmanager/values.yaml
alertmanager:
  config:
    global:
      resolve_timeout: 5m
    
    route:
      group_by: ['alertname', 'job']
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 12h
      receiver: 'console'
    
    receivers:
    - name: 'console'

replicaCount: 1

persistentVolume:
  enabled: true
  size: 2Gi