apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: alertmanager
  namespace: argocd
spec:
  project: default
  source:
    chart: alertmanager
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 0.19.0
    helm:
      values: |
        config:
          global:
            resolve_timeout: 1m  # Shorter for testing
          route:
            group_by: ['alertname']
            group_wait: 10s  # Shorter for testing
            group_interval: 10s  # Shorter for testing
            repeat_interval: 1h  # More frequent repeats
            receiver: 'console'
            routes:
              - match:
                  severity: warning
                receiver: 'console'
          receivers:
          - name: 'console'
        persistentVolume:
          enabled: true
          size: 2Gi
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true