apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
spec:
  project: default
  source:
    chart: prometheus
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 15.10.1
    helm:
      values: |
        server:
          persistentVolume:
            enabled: true
            size: 8Gi
          strategy:
            type: Recreate  # Moved here under server section
          global:
            scrape_interval: 15s
          alerting:
            alertmanagers:
              - static_configs:
                  - targets: ['alertmanager.monitoring.svc.cluster.local:9093']
                scheme: http
                timeout: 10s
        serverFiles:
          alerting_rules.yml:
            groups:
              - name: nginx.rules
                rules:
                  - alert: NginxHighCpuUsage
                    expr: sum(rate(container_cpu_usage_seconds_total{pod=~"nginx-.*"}[5m])) by (pod) > 0.00002
                    for: 1m  # Changed from 5m to 1m
                    labels:
                      severity: warning
                    annotations:
                      summary: "High CPU usage on {{ $labels.pod }}"
                      description: "Nginx pod {{ $labels.pod }} has high CPU usage (> 50%) for more than 1 minute."
          config:
            route:
              group_by: ['alertname']
              # Add this:
              routes:
                - match:
                    severity: warning
                  receiver: 'console'
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true