apiVersion: apps/v1
kind: Deployment
metadata:
  name: acr-test
  labels:
    app: acr-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: acr-test
  template:
    metadata:
      labels:
        app: acr-test
    spec:
      containers:
      - name: nginx
        image: aksdemoclusteracr.azurecr.io/nginx:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: acr-test
spec:
  selector:
    app: acr-test
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP
